Bellabeat Case Study
================
Kathryn Ference
10/28/2021

This is an analysis of a 2016 study of FitBit fitness tracker data
conducted by Fitabase, a San Diego-based research firm. The data was
generated by 33 respondents to a distributed study between March 12,
2016 and May 12, 2016.

This analysis will look at how this information can help Bellabeat, a
brand that produces smart devices targeted to promote women’s overall
health and well-being. With this analysis, we will explore ways to
optimize the Bellabeat app, which connects to Bellabeat’s devices and
provides users with health data related to their activity, sleep,
stress, menstrual cycle, and mindfulness habits. We are especially
interested in how this app data can be optimized in relation to
Bellabeat’s brand new smart device, Ivy, released in January 2021.

## Correlation in Daily Activities

First, we will look at the average daily activities logged per person
over time, and see if we find correlations between these variables.

To do this, take the dailyActivity\_merged sheet, remove any NULL
values, and remove the date column. There were many values logged over
time for each ID number, so to see the average of daily activities,
steps, calories, etc, for each person during this time period, average
each column by ID number:

``` r
load("~/no_date_df.RData")
mean_df <- aggregate(.~Id, no_date_df, mean)
```

To see correlations between variables, we calculate the correlations in
the data frame using the Pearson method. In the table, correlation
coefficients are displayed between -1 (a perfect negative correlation)
and 1 (a perfect positive correlation). Correlations are generally
significant below -.6 or above .6.

``` r
activityCorrs <- cor(mean_df, method="pearson")
print(activityCorrs)
```

    ##                                    Id   TotalSteps TotalDistance
    ## Id                        1.000000000  0.240109390   0.315943982
    ## TotalSteps                0.240109390  1.000000000   0.984909841
    ## TotalDistance             0.315943982  0.984909841   1.000000000
    ## TrackerDistance           0.312361103  0.983708932   0.999622834
    ## LoggedActivitiesDistance  0.289885659  0.206688202   0.200794106
    ## VeryActiveDistance        0.431212936  0.784653059   0.819969115
    ## ModeratelyActiveDistance  0.038390840  0.492113405   0.445104005
    ## LightActiveDistance      -0.005258013  0.723953947   0.718515526
    ## SedentaryActiveDistance  -0.055313732 -0.005839943   0.003507061
    ## VeryActiveMinutes         0.406765080  0.701374580   0.727350164
    ## FairlyActiveMinutes       0.081580951  0.477993234   0.436456443
    ## LightlyActiveMinutes     -0.167886962  0.510720403   0.452237458
    ## SedentaryMinutes         -0.019015481 -0.385461674  -0.320322157
    ## Calories                  0.476970080  0.436043228   0.546319734
    ##                          TrackerDistance LoggedActivitiesDistance
    ## Id                           0.312361103               0.28988566
    ## TotalSteps                   0.983708932               0.20668820
    ## TotalDistance                0.999622834               0.20079411
    ## TrackerDistance              1.000000000               0.17709533
    ## LoggedActivitiesDistance     0.177095332               1.00000000
    ## VeryActiveDistance           0.821133716               0.13072864
    ## ModeratelyActiveDistance     0.444926897               0.06472932
    ## LightActiveDistance          0.715889841               0.21668862
    ## SedentaryActiveDistance      0.003651034              -0.05224457
    ## VeryActiveMinutes            0.728404579               0.20899190
    ## FairlyActiveMinutes          0.436919313               0.03029609
    ## LightlyActiveMinutes         0.447930008               0.15577112
    ## SedentaryMinutes            -0.321925053              -0.09424594
    ## Calories                     0.546944472               0.23339581
    ##                          VeryActiveDistance ModeratelyActiveDistance
    ## Id                               0.43121294               0.03839084
    ## TotalSteps                       0.78465306               0.49211340
    ## TotalDistance                    0.81996912               0.44510400
    ## TrackerDistance                  0.82113372               0.44492690
    ## LoggedActivitiesDistance         0.13072864               0.06472932
    ## VeryActiveDistance               1.00000000               0.16402040
    ## ModeratelyActiveDistance         0.16402040               1.00000000
    ## LightActiveDistance              0.24791924               0.26265132
    ## SedentaryActiveDistance         -0.04931726              -0.18768496
    ## VeryActiveMinutes                0.88920580               0.18097595
    ## FairlyActiveMinutes              0.22161710               0.95801311
    ## LightlyActiveMinutes             0.02759006               0.11543425
    ## SedentaryMinutes                -0.04163279              -0.39824794
    ## Calories                         0.51161933               0.06197865
    ##                          LightActiveDistance SedentaryActiveDistance
    ## Id                              -0.005258013            -0.055313732
    ## TotalSteps                       0.723953947            -0.005839943
    ## TotalDistance                    0.718515526             0.003507061
    ## TrackerDistance                  0.715889841             0.003651034
    ## LoggedActivitiesDistance         0.216688623            -0.052244573
    ## VeryActiveDistance               0.247919236            -0.049317262
    ## ModeratelyActiveDistance         0.262651315            -0.187684957
    ## LightActiveDistance              1.000000000             0.170727492
    ## SedentaryActiveDistance          0.170727492             1.000000000
    ## VeryActiveMinutes                0.209327776            -0.105117332
    ## FairlyActiveMinutes              0.186805758            -0.217479611
    ## LightlyActiveMinutes             0.833552206             0.289466738
    ## SedentaryMinutes                -0.446362473             0.230947116
    ## Calories                         0.351100026            -0.026325427
    ##                          VeryActiveMinutes FairlyActiveMinutes
    ## Id                             0.406765080          0.08158095
    ## TotalSteps                     0.701374580          0.47799323
    ## TotalDistance                  0.727350164          0.43645644
    ## TrackerDistance                0.728404579          0.43691931
    ## LoggedActivitiesDistance       0.208991897          0.03029609
    ## VeryActiveDistance             0.889205797          0.22161710
    ## ModeratelyActiveDistance       0.180975949          0.95801311
    ## LightActiveDistance            0.209327776          0.18680576
    ## SedentaryActiveDistance       -0.105117332         -0.21747961
    ## VeryActiveMinutes              1.000000000          0.31314611
    ## FairlyActiveMinutes            0.313146114          1.00000000
    ## LightlyActiveMinutes           0.003218503          0.03015082
    ## SedentaryMinutes              -0.202915817         -0.38575600
    ## Calories                       0.629966188          0.15767991
    ##                          LightlyActiveMinutes SedentaryMinutes    Calories
    ## Id                               -0.167886962      -0.01901548  0.47697008
    ## TotalSteps                        0.510720403      -0.38546167  0.43604323
    ## TotalDistance                     0.452237458      -0.32032216  0.54631973
    ## TrackerDistance                   0.447930008      -0.32192505  0.54694447
    ## LoggedActivitiesDistance          0.155771118      -0.09424594  0.23339581
    ## VeryActiveDistance                0.027590062      -0.04163279  0.51161933
    ## ModeratelyActiveDistance          0.115434249      -0.39824794  0.06197865
    ## LightActiveDistance               0.833552206      -0.44636247  0.35110003
    ## SedentaryActiveDistance           0.289466738       0.23094712 -0.02632543
    ## VeryActiveMinutes                 0.003218503      -0.20291582  0.62996619
    ## FairlyActiveMinutes               0.030150822      -0.38575600  0.15767991
    ## LightlyActiveMinutes              1.000000000      -0.44035895 -0.00407536
    ## SedentaryMinutes                 -0.440358952       1.00000000 -0.07699961
    ## Calories                         -0.004075360      -0.07699961  1.00000000

As we are comparing a number of variables, the table is very difficult
to look at. In order to make it easier to view, we can plot this
correlation table to better see relationships between the variables:

``` r
library(corrplot)
```

    ## corrplot 0.90 loaded

``` r
corrplot(activityCorrs,type="upper",order="original",tl.col="black",tl.srt=45)
```

![](bellabeat-case-study_files/figure-gfm/correlation_plot_2-1.png)<!-- -->

Obviously there are strong correlations between steps and distance
(.98), as they essentially measure the same thing. There are also strong
correlations between distance traveled at various intensities and
minutes spent at those various intensities, which also is to be
expected. (If one spends time going distance at a very active pace, it
is to be expected that the minutes spent doing so will be very active
minutes, for example.)

There is a negative correlation between Sedentary minutes and almost
every other variable–the more time spent being sedentary, the fewer
total steps, total distance, and active minutes a person will get in a
day.

However, the ‘Calories’ variable produces some interesting and perhaps
unexpected correlations. There is no correlation between Sedentary
Minutes and calories (as one might expect), and the correlation between
Calories and Total Steps is also surprisingly weak–the correlation
coefficient is only .43. Instead, the strongest correlation between
Calories and activity level appears to be ‘Very Active Minutes’. This
would suggest that those users who are hoping to maximize their calories
burned should be maximizing active minutes rather than distance or
steps.

Considering this, for those smart device wearers whose goal is to lose
weight, it might be best to include app reminders and other cues that
encourage people to engage in high energy exercise rather than to
maximize total number of steps.

## Correlation between Activity and Sleep

There is a common belief that exercise during the day an improve sleep
for many people. However, our data did not show that activity levels had
any significant impact on total minutes asleep or total time in bed.

We found this by averaging the sleep minutes and time in bed for each
user and concatenating this with the activity sheet by Id number. The
resulting correlation plot was the following:

![](bellabeat-case-study_files/figure-gfm/activity_sleep%20corelation%20plot-1.png)<!-- -->

Although there is a very slight negative correlation, these numbers were
not statistically significant–essentially, no relationship exists.
However, number of minutes asleep and total time in bed does not give us
information on the quality of sleep users had, so more information on
the quality of individuals’ sleep.

Theoretically, we could get a sense of the quality of each individuals’
sleep through the minuteSleep\_merged dataset, as this set tracks the
quality of each persons’ sleep over the course of each night using the
values 1 for ‘awake’, 2 for ‘restless’, and 3 for ‘awake’. More 2s and
3s should indicate more restless, and therefore poorer quality, sleep.

However, the users’ nightly tracking of sleep is very inconsistent. Some
users sleep with their devices every night, providing very high quality
data. Others, however, rarely use the feature. Here are the number of
nights each user logged their sleep over the course of the study:

``` r
load("~/minute_sleep_table.RData")
print(minute_sleep_table)
```

    ##            Id Freq
    ## 1  1503960366   25
    ## 2  1644430081    5
    ## 3  1844505072    5
    ## 4  1927972279    8
    ## 5  2026352035   32
    ## 6  2320127002    1
    ## 7  2347167796   18
    ## 8  3977333714   28
    ## 9  4020332650   11
    ## 10 4319703577   29
    ## 11 4388161847   26
    ## 12 4445114986   28
    ## 13 4558609924    8
    ## 14 4702921684   31
    ## 15 5553957443   32
    ## 16 5577150313   28
    ## 17 6117666160   21
    ## 18 6775888955    3
    ## 19 6962181067   31
    ## 20 7007744171    2
    ## 21 7086361926   27
    ## 22 8053475328    3
    ## 23 8378563200   32
    ## 24 8792009665   15

This table only includes the users who did track any sleep data over the
course of the study–9 of the users had no sleep data recorded at all
during the course of the study. This means 27% of the consumers in this
study did not access or make use of this feature at all!

This is worth noting. Bellabeat is a company that places utmost focus on
lifestyle and overall wellness. Sleep is a key part of the daily
wellness score users are given. If 27% of users are not even accessing
the the sleep tracking feature, this could impact the ability of the app
to provide relevant data on wellness to users.

Are there particular users who are more or less likely to track their
sleep data? We will be able to determine this using a measure called
k-means clustering.

## Correlation between Activity and Heart Rate

Unlike the correlation between activity and sleep, our data did show
some correlation between daily steps, activity levels and median heart
rate.

To see the average heart rates, we uploaded the
heartrate\_seconds\_merged data set, then aggregated by Id to calculate
the median heart rate per user. Median is a better measure here than
mean, because we are interested in looking at resting heart rate for
each user. If a user is exercising regularly, their heart rate may be
higher, but even the most ardent athletes will be at rest most of the
time. Therefore, the median heart rate is much more likely to be close
to the user’s resting heart rate.

Then, we can merge this heart rate date with the activity data by user
Id.

``` r
load("~/heartrate.RData")
load("~/mean_activity_df.RData")
heartrate_median <- aggregate(Value ~ Id, heartrate, median)
heartrate_merge <- merge(mean_activity_df, heartrate_median, by="Id")
```

Just to note, there was only heart rate data available for 14 of the
users, so we should avoid drawing too many conclusions about the full
data set from this subset. Unlike sleep, heart rate is not something
manually entered by the user, so it is very likely that the other 19
participants in the study were using Fitbit trackers that did not have
heart rate monitors. This data is from 2016, when heart rate monitoring
was less common in FitBit trackers; if this study were to be replicated
in 2021, this percentage would no doubt be higher. That is a limitation
of this data set.

Among the 42% of users whose smart devices featured heart rate monitors,
we can see some interesting trends. First, there is somewhat of a
correlation between activity rates and resting heart rate in these
users:

``` r
heartrate_merge <- heartrate_merge[ -c(1, 5, 7:9, 11:12)]
heartrateMatrix <- cor(heartrate_merge, method="pearson")
heartratePlot <- corrplot(heartrateMatrix,type="upper",order="original",tl.col="black",tl.srt=45)
```

![](bellabeat-case-study_files/figure-gfm/Heart%20Rate%20Correlation-1.png)<!-- -->

Much like with the correlations between activity rate and calories
burned, the strongest correlation between activity and resting heart
rate was among those users who had the most ‘very active minutes’ during
the day, although all categories seemed to have some affect. More
sedentary minutes means a slightly higher resting heart rate.

## K-Means Clustering

K-means clustering, put simply, is a method that attempts to divide
observations into smaller groups that have variables in common. Each
observation belongs to the cluster with the nearest mean, which serves
as the prototype of the cluster. This process can give us better insight
into the types of people using smart apps and what these groups may have
in common.

The first step to k means clustering is to figure out the number of
groups, k, that the dataset can be divided into. There are a few
different ways to do this. Three of them are an elbow plot, a silhouette
plot, and a gap statistic.

    ## Loading required package: ggplot2

    ## Welcome! Want to learn more? See two factoextra-related books at https://goo.gl/ve3WBa

![](bellabeat-case-study_files/figure-gfm/K%20Cluster%20Plot-1.png)<!-- -->![](bellabeat-case-study_files/figure-gfm/K%20Cluster%20Plot-2.png)<!-- -->![](bellabeat-case-study_files/figure-gfm/K%20Cluster%20Plot-3.png)<!-- -->

As can be seen above, sometimes these measures do not agree, so best
judgement must be used. In this instance, splitting the difference
between the plots and using a k of 3 is particularly instructive:

``` r
final <- kmeans(kmeans_df, 4)
print(final)
```

    ## K-means clustering with 4 clusters of sizes 7, 14, 7, 5
    ## 
    ## Cluster means:
    ##        Freq TotalSteps TotalDistance TrackerDistance VeryActiveDistance
    ## 1  8.714286   5256.272      3.657930        3.657930          0.5611017
    ## 2 18.714286   8128.045      5.791830        5.787084          1.1960958
    ## 3 12.000000  12487.519      9.215364        9.152561          3.7402304
    ## 4  8.400000   2027.367      1.393357        1.393357          0.1961020
    ##   ModeratelyActiveDistance LightActiveDistance VeryActiveMinutes
    ## 1                0.2048895            2.879846          5.825267
    ## 2                0.6877391            3.773498         22.248305
    ## 3                0.9524576            4.458581         42.760794
    ## 4                0.1305013            1.055578          3.722136
    ##   FairlyActiveMinutes LightlyActiveMinutes SedentaryMinutes Calories
    ## 1            4.285141            180.68034        1099.2592 1899.389
    ## 2           16.100528            224.61491         881.0585 2425.339
    ## 3           22.274713            221.13097         974.4528 2549.141
    ## 4            5.252306             72.58294        1224.2392 2045.235
    ## 
    ## Clustering vector:
    ##  [1] 3 1 2 4 4 3 1 1 2 2 2 3 4 1 2 3 1 2 2 2 2 2 1 4 2 3 2 3 1 2 2 4 3
    ## 
    ## Within cluster sum of squares by cluster:
    ## [1]  5788515 17251506 28622669  2285939
    ##  (between_SS / total_SS =  87.2 %)
    ## 
    ## Available components:
    ## 
    ## [1] "cluster"      "centers"      "totss"        "withinss"     "tot.withinss"
    ## [6] "betweenss"    "size"         "iter"         "ifault"

![](bellabeat-case-study_files/figure-gfm/K%20Means%20Cluster%20Plot-1.png)<!-- -->

## Types of smart device users

The users in the data set can be divided into 4 basic types in their use
of their smart devices.

### Group 1

These are the athletes. They have the largest number of total steps
(12,487 per day on average, with a couple of outliers at 14763 and
16040), and spend much longer time and go much further distance at a
very active intensity level than the other two groups (42 minutes on
average, vs 23, 7 and 3, and about 3 and a half miles on average, vs
1.2, .64, and .17). They are not particularly engaged in tracking their
sleep (the only tracked their sleep an average of 12 days), and are
using their devices primarily for their fitness goals. They make up 21%
of users.

### Group 3

These are the wellness trackers. They might also be called the
‘all-around’ user. They take fewer steps than the athletes, but still
track a solidly large number of steps (8225 per day, on average). They
tend to be all-around active, and they are much, much more likely to
track their sleep on a nightly basis (over 20 nights on average) than
the other three group. They make up 39% of all users.

Based on Bellabeat’s current marketing focus on wellness, mindfulness,
and overall health, this group could be said to be Bellabeat’s current
primary target audience.

### Group 2

This is a relatively sedentary group of users, at least compared to
groups 1 and 3. They are somewhat active, taking 5668 steps per day on
average, with some very active minutes (7 on average) and about the same
number of lightly active minutes per day as groups 1 and 3 (212 on
average, compared to 221 and 216). However, they are fairly sedentary
overall. They made up 21% of the study.

This group is the second-best target for Bellabeat’s marketing strategy.
Although they are not as active now, they are lightly active and will
track some of their nightly sleep. Although gender was not included in
this data set, this group had the lowest calories burned per day even
though they were not the least active group. Calories burned are highly
correlated to body mass, so this group is likely to be smaller in
stature, which means that this group may contain more women. Since women
are Bellabeat’s target demographic, this also makes them more likely to
be interested in the company’s products.

### Group 4

This is the most sedentary group of the 4, only taking 2329 steps per
day and logging almost no minutes of active exercise. They also tracked
the fewest nights of sleep of the study (7). and spend very little time
in very active exercise (only 3 minutes on average). Unlike Group 2,
they had very few active minutes (only 77), and they have far more
sedentary minutes than the other groups on a daily basis (1223, vs 865,
974, and 1079). They made up 18% of the study.

Interestingly, even though they were significantly more sedentary than
Group 2, they burned more calories than Group 2. This would suggest that
there are other variables at play here that are not available with this
data set–possibly a size or even potentially a gender difference between
the two groups, as larger people are more likely to burn more calories
regardless of daily activity.

This group is the least likely to be a target consumer of Bellabeat’s
products.

## Conclusions

In this analysis of smart device usage, we have explored the ways that
users’ activities affect their calories burned, sleep quantity, and
resting heart rate. Science has known for some time that that these
variables are correlated, but what is most useful about this data is
that the smart device can track and demonstrate these correlations in
real time to the user.

In order to help users see the most improvement in their calories burned
and resting heart rate, the Bellabeat app should encourage users to
exercise at a very high level of activity as much as possible. If the
company is able to demonstrate that users are able to make real
improvements in these areas over time by using the feedback data from
the app, the marketing department can use these results in their
campaigns. Proof that Bellabeat can demonstrate real results over time
will be of particular interest to users who are seeking to improve their
health.

We can also understand how consumers use these devices on a day to day
basis in order to better understand users’ needs. We can see from the
data in the study that all 33 users tracked their total steps, distance,
sedentary minutes, and calories using their smart devices. Activity
tracking is by far the most used feature of the devices. Of these users,
73% chose to wear their devices to bed to track their sleep data,
although none did so every night and over half only logged a few days
here and there. A follow-up survey to these users to better understand
why they were not wearing their devices to bed more regularly would be
of immense help with future product development and app optimization.

At the time of this survey, only 42% of users had devices that tracked
heart rate monitoring data. Among Group 3, the group that best resembles
Bellabeat’s target audience, this number was even smaller, at 38%. This
could suggest that heart rate monitoring is less important to this
group. However, as previously mentioned, this number would likely be
higher in a study conducted in 2021 as heart rate monitoring has
proliferated in more and more devices. Bellabeat itself is relatively
new to heart rate monitoring in its smart devices; only their newest
device, Ivy, has this feature, and it was released in 2021.

Bellabeat’s app provides a wealth of data to the user, including resting
heart rate, respiratory rate, and cardiac coherence, and helps users
understand their stress levels, wellness, and readiness to face the day.
Bellabeat’s app also tracks activity to add more movement to their day.
The app could be even better if the app could combine activity and
wellness to help users understand how their daily activity affects their
resting heart rate, sleep, and other factors. We can understand this
relationship using users’ data and correlation between variables.

Through this data, we were also able to segment the users into those
more or less likely to be similar to Bellabeat’s market segment.
Understanding how device use relates to market segmentation could
improve Bellabeat’s reach to smart device users who are currently using
devices from other brands but might be more interested in Bellabeat’s
offerings.

Additional data could certainly expand on these findings. A more recent
study would help us understand how smart device usage has evolved over
time. Market research surveys could provide eye-opening insight into why
device users behave the way they do, which would add valuable insight to
the thinking behind the numbers. And, as women are an explicit
demographic of Bellabeat’s products, data about how women use their
devices would be extremely helpful in understanding what this market
segments needs and wants from the smart devices they use.
